# Generated by Django 5.2.1 on 2025-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubbing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DubbingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('status', models.CharField(default='pending', max_length=32)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='dubbed/')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
