# Generated by Django 4.2.23 on 2025-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dubbing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dubbingjob",
            name="step_status",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
