# Generated by Django 4.2.23 on 2025-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dubbing", "0005_dubbingjob_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="dubbingjob",
            name="extracted_audio",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
        migrations.AddField(
            model_name="dubbingjob",
            name="translated_subtitles",
            field=models.TextField(blank=True, null=True),
        ),
    ]
