# Generated by Django 4.2.23 on 2025-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dubbing", "0006_dubbingjob_extracted_audio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dubbingjob",
            name="dubbed_audio_file",
            field=models.FileField(blank=True, null=True, upload_to="dubbed_audio/"),
        ),
    ]
