# Generated by Django 4.2.23 on 2025-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dubbing", "0007_dubbingjob_dubbed_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="dubbingjob",
            name="quality",
            field=models.CharField(default="medium", max_length=20),
        ),
    ]
